# Generated by Django 3.2.8 on 2022-01-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220107_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='User',
            new_name='user',
        ),
    ]
